language: python

sudo: false

python:
  - 3.7

addons:
  apt:
    packages:
    - iverilog
    - verilator

install:
  - pip install pytest pytest-pythonpath jinja2 pyverilog veriloggen numpy onnx torch torchvison

script:
  - python -m pytest --sim=verilator tests
